import io
import csv
from xml.sax.saxutils import escape
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from app.analysis.service import get_assessment

def safe_escape(text) -> str:
    if text is None:
        return ""
    return escape(str(text))

def generate_pdf_report(assessment_id: str, user_id: str) -> io.BytesIO:
    """Generate a detailed PDF report using ReportLab."""
    data = get_assessment(assessment_id, user_id)
    
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    styles = getSampleStyleSheet()
    
    # Custom colors
    navy = colors.HexColor("#1e3a8a")
    blue = colors.HexColor("#3b82f6")
    green = colors.HexColor("#10b981")
    red = colors.HexColor("#ef4444")
    
    # Custom styles
    title_style = ParagraphStyle(
        'MainTitle', parent=styles['Heading1'], fontSize=24, spaceAfter=20, textColor=navy, alignment=TA_CENTER
    )
    subtitle_style = ParagraphStyle(
        'Subtitle', parent=styles['Heading2'], fontSize=16, spaceAfter=15, textColor=blue, alignment=TA_CENTER
    )
    heading2 = ParagraphStyle(
        'SectionHeader', parent=styles['Heading2'], fontSize=14, spaceBefore=20, spaceAfter=10, textColor=navy
    )
    normal = ParagraphStyle('Normal', parent=styles['Normal'], fontSize=10, spaceAfter=8, textColor=colors.black)
    bullet = ParagraphStyle('Bullet', parent=styles['Normal'], fontSize=10, spaceAfter=4, leftIndent=15)
    question_style = ParagraphStyle('Question', parent=styles['Normal'], fontSize=11, spaceAfter=6, fontName='Helvetica-Bold')
    answer_style = ParagraphStyle('Answer', parent=styles['Normal'], fontSize=10, spaceAfter=12, textColor=colors.darkgray)
    
    elements = []
    
    # ─── Cover Page / Summary ───
    elements.append(Paragraph("Career Prep AI", subtitle_style))
    elements.append(Paragraph("Personalized Career Assessment Report", title_style))
    elements.append(Spacer(1, 20))
    
    elements.append(Paragraph(f"<b>Target Role:</b> {safe_escape(data.get('target_role'))}", normal))
    elements.append(Paragraph(f"<b>Date:</b> {safe_escape(data.get('created_at', '').split('T')[0])}", normal))
    
    prof = data.get("profile", {})
    if prof:
        if prof.get("name"):
            elements.append(Paragraph(f"<b>Candidate:</b> {safe_escape(prof.get('name'))}", normal))
        if prof.get("email"):
            elements.append(Paragraph(f"<b>Email:</b> {safe_escape(prof.get('email'))}", normal))
            
    if data.get("job_description_text"):
        elements.append(Spacer(1, 10))
        elements.append(Paragraph(f"<b>Custom Job Description Analyzed:</b> Yes", normal))
    
    elements.append(Spacer(1, 20))
    
    # Readiness Score block
    elements.append(Paragraph(f"<font size=18 color='#1e3a8a'><b>Readiness Score: {data.get('readiness_score', 0)}%</b></font>", normal))
    
    elements.append(Spacer(1, 20))
    elements.append(PageBreak())
    
    # ─── Gap Analysis ───
    elements.append(Paragraph("Skill Gap Analysis", heading2))
    
    table_data = [["Skill Name", "Status", "Requirement"]]
    for s in data.get("skills", []):
        if s.get("status") == "present":
            status = "Present"
        else:
            status = "Missing"
            
        req = "Required" if s.get("is_required", True) else "Good to have"
        table_data.append([s.get('name', 'Unknown'), status, req])
        
    t = Table(table_data, colWidths=[200, 100, 150])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), navy),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0,0), (-1,0), 10),
        ('TOPPADDING', (0,0), (-1,0), 10),
        ('BACKGROUND', (0,1), (-1,-1), colors.white),
        ('GRID', (0,0), (-1,-1), 0.5, colors.lightgrey)
    ]))
    
    # Add color to specific rows
    for i, row in enumerate(table_data[1:], 1):
        if row[1] == "Present":
            t.setStyle(TableStyle([('TEXTCOLOR', (1,i), (1,i), green)]))
        else:
            t.setStyle(TableStyle([('TEXTCOLOR', (1,i), (1,i), red)]))
            
    elements.append(t)
    elements.append(Spacer(1, 20))
    elements.append(PageBreak())
    
    # ─── Interview Prep ───
    elements.append(Paragraph("Personalized Interview Preparation", heading2))
    elements.append(Paragraph("Tailored questions generated by AI based on your profile and skill gaps.", normal))
    elements.append(Spacer(1, 10))
    
    for i, q in enumerate(data.get("questions", []), 1):
        elements.append(Paragraph(f"{i}. {safe_escape(q.get('question'))}", question_style))
        category_str = safe_escape(q.get('category', '')).capitalize()
        skill_str = safe_escape(q.get('skill', 'General'))
        elements.append(Paragraph(f"<b>Category:</b> {category_str}  |  <b>Target Skill:</b> {skill_str}", bullet))
        
        if q.get('answer'):
            # Replace newlines with <br/> after escaping
            ans = safe_escape(q.get('answer')).replace('\n', '<br/>')
            elements.append(Paragraph(f"<b>Suggested Answer:</b><br/>{ans}", answer_style))
        
        if q.get('interviewer_intent'):
            elements.append(Paragraph(f"<b>Interviewer Intent:</b> {safe_escape(q.get('interviewer_intent'))}", answer_style))
            
        elements.append(Spacer(1, 15))

    elements.append(PageBreak())
    
    # ─── Recommended Courses ───
    if data.get("courses"):
        elements.append(Paragraph("Learning Roadmap & Recommendations", heading2))
        elements.append(Paragraph("Courses recommended to close your skill gaps.", normal))
        elements.append(Spacer(1, 10))
        
        for skill, course_list in data.get("courses", {}).items():
            elements.append(Paragraph(f"<b>Skill: {safe_escape(skill)}</b>", ParagraphStyle('Sub', parent=styles['Heading3'], textColor=blue)))
            for c in course_list[:3]:  # Top 3 per skill
                link = f"<a href='{safe_escape(c.get('url'))}' color='blue'>Click here to view course</a>" if c.get('url') else "No link available"
                elements.append(Paragraph(f"• <b>{safe_escape(c.get('title'))}</b> ({safe_escape(c.get('platform'))})", normal))
                elements.append(Paragraph(f"  {link}", bullet))
            elements.append(Spacer(1, 10))

    doc.build(elements)
    buffer.seek(0)
    return buffer

def generate_csv_export(assessment_id: str, user_id: str) -> io.StringIO:
    """Export assessment data to CSV."""
    data = get_assessment(assessment_id, user_id)
    
    buffer = io.StringIO()
    writer = csv.writer(buffer)
    
    # Write summary
    writer.writerow(["Assessment ID", data["id"]])
    writer.writerow(["Target Role", data["target_role"]])
    writer.writerow(["Readiness Score", data["readiness_score"]])
    writer.writerow(["Date", data["created_at"]])
    writer.writerow([])
    
    # Write Skills
    writer.writerow(["Skill Name", "Status", "Required"])
    for s in data["skills"]:
        writer.writerow([s["name"], s["status"], s.get("is_required", True)])
    
    writer.writerow([])
    
    # Write Questions
    writer.writerow(["Category", "Question", "Target Skill"])
    for q in data["questions"]:
        writer.writerow([q["category"], q["question"], q.get("skill", "")])
        
    buffer.seek(0)
    return buffer
